#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')
BATTERY_ICON=0

URGENT_VALUE=10

if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
  BATTERY_ICON=""
elif [[ "${BATTERY_POWER}" -le 25 ]]; then
  BATTERY_ICON=""
elif [[ "${BATTERY_POWER}" -le 50 ]]; then
  BATTERY_ICON=""
elif [[ "${BATTERY_POWER}" -le 75 ]]; then
  BATTERY_ICON=""
else
  BATTERY_ICON=""
fi




if [[ "${BATTERY_STATE}" = "Charging" ]]; then
  echo "${BATTERY_ICON} ${BATTERY_POWER}%+"
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
  echo "${BATTERY_ICON} ${BATTERY_POWER}%-"
else
  echo "${BATTERY_ICON} ${BATTERY_POWER}%"
fi

if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi