#!/bin/bash
# Based on http://openweathermap.org/current

API_KEY="ad5c723ce0c47eba0801830782894770"

# Check on http://openweathermap.org/find
CITY_ID="3054643" #Budapest, te csodás

URGENT_LOWER=-30
URGENT_HIGHER=50

ICON=0

SYMBOL_CELSIUS="℃"

WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=metric"

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | head -1 | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_ICON=$(echo "${WEATHER_INFO}" | grep -o -e '\"icon\":\"[a-Z0-9]*\"'| head -1 | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_FEEL=$(echo "${WEATHER_INFO}" | grep -o -e '\"feels_like\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
# no more -0 degrees
if [[ "${WEATHER_TEMP}" = "-0" ]]; then
  WEATHER_TEMP="0"
fi
if [[ "${WEATHER_FEEL}" = "-0" ]]; then
  WEATHER_FEEL="0"
fi

if [[ "${WEATHER_ICON}" = "01d" ]]; then
  ICON=""
elif [[ "${WEATHER_ICON}" = "01n" ]]; then
  ICON=""
elif [[ "${WEATHER_ICON}" = "02d" ]]; then
  ICON=""
elif [[ "${WEATHER_ICON}" = "02n" ]]; then
  ICON=""
elif [[ "${WEATHER_ICON}" = "03d" ]] || [[ "${WEATHER_ICON}" = "03n" ]] || [[ "${WEATHER_ICON}" = "04d" ]] || [[ "${WEATHER_ICON}" = "04n" ]]; then
  ICON=""
elif [[ "${WEATHER_ICON}" = "09d" ]] || [[ "${WEATHER_ICON}" = "09n" ]]; then
  ICON=""
elif [[ "${WEATHER_ICON}" = "10d" ]]; then
  ICON=""
elif [[ "${WEATHER_ICON}" = "10n" ]]; then
  ICON=""
elif [[ "${WEATHER_ICON}" = "11d" ]] || [[ "${WEATHER_ICON}" = "11n" ]]; then
  ICON=""
elif [[ "${WEATHER_ICON}" = "13d" ]] || [[ "${WEATHER_ICON}" = "13n" ]]; then
  ICON=""
elif [[ "${WEATHER_ICON}" = "50d" ]] || [[ "${WEATHER_ICON}" = "50n" ]]; then
  ICON=""
else
  ICON=${WEATHER_ICON}
fi

echo "${ICON} ${WEATHER_TEMP}${SYMBOL_CELSIUS} (${WEATHER_FEEL}${SYMBOL_CELSIUS})"
echo "${ICON} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"

if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
  exit 33
fi